UPDATE pop SET "country" = NULL WHERE "country" = '-';
UPDATE pop SET "year" = NULL WHERE "year" = '-';
UPDATE pop SET "Total Population" = NULL WHERE "Total Population" = '-';
UPDATE pop SET "Urban Population" = NULL WHERE "Urban Population" = '-';
UPDATE pop SET "Rural Population" = NULL WHERE "Rural Population" = '-';
UPDATE pop SET "Population Density" = NULL WHERE "Population Density" = '-';
UPDATE pop SET "Life Expectancy" = NULL WHERE "Life Expectancy" = '-';
UPDATE pop SET "Birth Rate" = NULL WHERE "Birth Rate" = '-';
UPDATE pop SET "Death Rate" = NULL WHERE "Death Rate" = '-';
UPDATE pop SET "Fertility Rate" = NULL WHERE "Fertility Rate" = '-';
UPDATE pop SET "Infant Mortality Rate" = NULL WHERE "Infant Mortality Rate" = '-';
UPDATE pop SET "Growth Rate" = NULL WHERE "Growth Rate" = '-';
